name: Daily DB Backup To CST

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install psycopg2-binary python-dotenv

    - name: DB Backup & Upload
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        CST_AK: ${{ secrets.CST_AK }}
        CST_SK: ${{ secrets.CST_SK }}
        CST_BUCKET: ${{ secrets.CST_BUCKET }}
      run: |
        python -m tasks.db_backup_task
